-- SQLite

DROP TABLE IF EXISTS personaje;
CREATE TABLE IF NOT EXISTS personaje(
    persId         integer PRIMARY KEY,
    persNombre     text
);
DROP TABLE IF EXISTS frase;
CREATE TABLE IF NOT EXISTS frase(
    fraseId         integer PRIMARY KEY,
    frase           text,
    persId          integer,
    FOREIGN KEY (persId) REFERENCES personaje(persId)
);

INSERT INTO personaje(persNombre)
VALUES  ('Homero Simpson'),
        ('Bart Simpson'),
        ('Marge Bouvier'),
        ('Helen Alegria'),
        ('Barney Gomez'),
        ('Abe Simpson'),
        ('Homero Bart Marge Simpson')
;

INSERT INTO frase(frase, persId)
VALUES  ('A la grande le puse Cuca.', 1),
        ('¡¿Alguien quiere pensar en los niños?!', 4),
        ('Tiene todo el dinero del mundo, pero hay algo que no puede comprar… Un dinosaurio.', 1),
        ('¡No vives de ensalada!', 7),
        ('¿Ah, si? ¿Y si era tan listo por qué se murió?', 1),
        ('Disimula y ve despacio hacia el pastel.', 1),
        ('¡Oh, no! ¡Elecciones! ¿Es uno de esos días en que cierran las tabernas, no es cierto?', 5),
        ('Vive deprisa, muere joven y deja un cadáver obeso.', 2),
        ('Mi Homero no es comunista. Podrá ser mentiroso, puerco, idiota, comunista, pero nunca una estrella de porno.', 6),
        ('Niños: Hicieron su esfuerzo y fracasaron miserablemente. La lección es: nunca se esfuercen.', 1)
;

SELECT * FROM personaje;
SELECT * FROM frase;

SELECT  fraseId,
        frase,
        personaje.persNombre
FROM frase
LEFT JOIN personaje ON frase.persId = personaje.persId;


DROP TABLE IF EXISTS capitulo;
CREATE TABLE IF NOT EXISTS capitulo(
    capId           integer PRIMARY KEY,
    capNro          integer,
    capNombre       TEXT,
    capTemporada    int,
    capDesc         TEXT,
    capTime         int,
    capNroTot       int
);

INSERT INTO capitulo(capNro, capNombre, capTemporada, capDesc, capTime, capNroTot)
VALUES
    (1,'Especial de navidad',1,'Homero no cobra el bono de Navidad, y el tatuaje de Bart se come el fondo de emergencia.',24,1),
    (2,'Bart es un genio',1,'Bart pasa a una escuela para superdotados tras cambiar la prueba de aptitud con otro niño.',24,2),
    (3,'La odisea de Homero',1,'Homero pierde el trabajo por negligente. Acto seguido, se vuelve activista de seguridad.',24,3),
    (4,'Una familia modelo',1,'Después de ver que otras familias se llevan bien, Homero obliga a Marge y los niños a ir a terapia.',24,4),
    (5,'El general Bart',1,'Bart le pide consejos al abuelo, que lo lleva a un entrenamiento militar.',24,5),
    (6,'La depresión de Lisa',1,'Lisa ahoga las penas en el blues. Homero toma clases para ganarle a Bart en un videojuego de box.',24,6),
    (7,'La llamada de los Simpson',1,'Los Simpson derrapan con la casa rodante. Homero y Bart buscan ayuda, se pierden y quedan sin ropa.',24,7),
    (8,'El héroe sin cabeza',1,'Bart hace algo que escandaliza a todos, incluso a los nuevos amigos que quería impresionar.',24,8),
    (9,'Un momento de decisión',1,'El regalo de Homero a Marge la lleva a jugar bolos con un instructor que le enseña “muchas cosas”.',24,9),
    (10,'La correría de Homero',1,'Bart toma una foto de Homero con una bailarina sexy en una despedida de solteros.',24,10),
    (11,'Intercambio cultural',1,'Bart salva a Francia tras hacer volar a la mama del director Skinner con un petardo.',24,11),
    (12,'Krusty va a la cárcel',1,'Krusty el Payaso, el héroe televisivo de Bart, va preso por un robo, y Homero atestigua contra el.',24,12),
    (13,'Una noche encantadora',1,'Homero y Marge dejan a los niños con una niñera que es famosa en TV y no por cariñosa.',24,13),
    (1,'Bart reprueba',2,'Bart le enseña al cerebro de la clase a no ser un ñoño, pero le copia demasiado bien y se preocupa.',24,14),
    (2,'Simpson y Dalila',2,'Homero consigue un asenso, la llave del baño para ejecutivos y un secretario invaluable.',24,15),
    (3,'Las casitas del terror',2,'Historias sobre una casa embrujada, alienígenas y una interpretación del poema “El cuervo”.',24,16),
    (4,'Dos autos en la cochera y tres ojos en cada pez',2,'El señor Burns quiere ser gobernador para desregular la energía nuclear y mantener activa su planta.',24,17),
    (5,'Homero el Animador',2,'El éxito de Homero como mascota de un equipo de ligas menores le da una chance en las ligas mayores.',24,18),
    (6,'La sociedad de los golfistas muertos',2,'Lisa le da consejos a Bart para manejar la presión de una rivalidad de minigolf con el vecino.',24,19),
    (7,'Bart contra el Día de Gracias',2,'En el Día de Acción de Gracias, Bart huye tras destrozar accidentalmente el centro de mesa de Lisa.',24,20),
    (8,'Bart, el temerario',2,'Bart descubre su razón de ser después de un evento espectacular: desafiar a la muerte,',24,21),
    (9,'Tomy, Daly y Marge',2,'Las protestas de Marge contra la violencia en las caricaturas llevan a un renacimiento cultural.',24,22),
    (10,'Bart es atropellado',2,'Un abogado sugiere aprovechar el choque de Bart con el auto del señor Burns para hacer dinero.',24,23),
    (11,'Aviso de Muerte',2,'Homero prueba el sushi, pero el pez globo que comió podría ser el bocado más peligroso de su vida.',24,24),
    (12,'Los años que vivimos',2,'Marge y Homero cuentan la historia de la primera vez que se vieron y del baile de graduación.',24,25),
    (13,'No robarás',2,'Lisa descubre que el castigo por robar es el infierno y se niega a ver TV pirateada.',24,26),
    (14,'El último tren',2,'El director Skinner se enamora de la tía Patty, y Bart le saca ventajas a la situación.',24,27),
    (15,'Donde estás hermano mío',2,'El medio hermano de Homero comete el error de darle un trabajo importante.',24,28),
    (16,'El perro de Bart reprueba',2,'El perro de Bart destroza los zapatos nuevos de Homero y termina en una escuela de obediencia.',24,29),
    (17,'Nuestros años felices',2,'Tras perder a su amada, el abuelo queda con el corazón roto y la billetera llena.',24,30),
    (18,'Pinceles con alma',2,'Marge pinta un retrato muy vívido del señor Burns.',24,31),
    (19,'El sustituto de Lisa',2,'Homero no está a la altura del maestro de Lisa, y Bart pasa por lo mismo con su rival.',24,32),
    (20,'La guerra de los Simpson',2,'Homero y Marge van a un retiro matrimonial, donde él atrapa un pez legendario… y algo más.',24,33),
    (21,'Tres hombres y una historieta',2,'Bart gana menos de lo esperado, así que se une a Milhouse y Martin para comprar una historieta.',24,34),
    (22,'Sangre nueva',2,'La sangre de Bart salva al señor Burns, que luego recibe una carta desagradable de Homero.',24,35),
    (1,'El patriotismo de Lisa',3,'Bart se sube a un avión mítico, y Lisa lucha por salvar el bosque de Springfield.',24,36),
    (2,'El día que cayó Flanders',3,'Ned Flanders anuncia que abrirá una tienda de productos para zurdos.',24,37),
    (3,'El pequeño padrino',3,'Mientras el resto de la clase disfruta de la excursión, Bart se mete en la mafia.',24,38),
    (4,'Homero al diccionario',3,'Homero evita una catástrofe en la planta nuclear y recibe elogios, pero siente que no lo merece.',24,39),
    (5,'De tal padre tal payaso',3,'En una cena con los Simpson, Krusty el Payaso revela que está distanciado de su padre rabino.',24,40),
    (6,'Las casitas del terror II',3,'Maggie pide un deseo, Bart domina Springfield, y Homero dona su cerebro a la ciencia.',24,41),
    (7,'El pony de Lisa',3,'Homero le compra un pony a Lisa, pero ahora necesita un segundo empleo en la tienda de Apu.',24,42),
    (8,'Tardes de trueno',3,'Homero ayuda a Bart a armar un auto de carreras. El resultado no es óptimo, pero su relación mejora.',24,43),
    (9,'Llamarada Moe',3,'Moe usa la receta para un cóctel de Homero sin darle crédito y su bar florece.',24,44),
    (10,'Burns y los alemanes',3,'Los alemanes toman control de la planta del señor Burns y pronto descubren que salieron perdiendo.',24,45),
    (11,' Me casé con Marge',3,'En una retrospectiva, Homero busca trabajo en la planta nuclear de Springfield.',24,46),
    (12,'Bart y la radio',3,'Bart le hace creer al pueblo que hay un niño atrapado en un pozo.',24,47),
    (13,'Los pronósticos de Lisa',3,'Homero descubre el talento de Lisa para las apuestas y no pierden el tiempo.',24,48),
    (14,'Homero se queda solo',3,'Marge va a un spa y deja a Bart y Lisa con Patty y Selma, y a Maggie con Homero…',24,49),
    (15,'Bart, el amante',3,'Bart contesta un anuncio personal personificando un amante perfecto para vengarse de su maestra.',24,50),
    (16,'Homero al bat',3,'Homero domina al equipo de softball de la empresa hasta que el señor Burns contrata profesionales.',24,51),
    (17,'Vocaciones distintas',3,'Una prueba vocacional determina que Lisa no se convertirá la saxofonista que tanto sueña ser.',24,52),
    (18,'Nuestro mejor amigo',3,'La fiebre de la lotería se apodera de Springfield, y justo el perro necesita una cirugía costosa.',24,53),
    (19,'Homero, el campirano',3,'Homero escapa a un bar de vaqueros, donde descubre a la hermosa cantante Lurleen Lumpkin,',24,54),
    (20,'El viudo negro',3,'Bob Patiño reaparece y quiere casarse con Selma, pero Bart está convencido de que trama algo.',24,55),
    (21,'El rock de Otto',3,'Otto pierde la licencia y se muda con los Simpson, que intentan ayudarlo a recuperar el trabajo.',24,56),
    (22,'Milhouse se enamora',3,'Tras una clase de educación sexual, Milhouse se enamora de la nueva de la clase, la bella Samantha.',24,57),
    (23,'Él es mi hermano',3,'Burns descubre que Homero es estéril y lo consuela con un premio presentado por Joe Frazier.',24,58),
    (1,'Kampo Krusty',4,'Bart y Lisa van al Campamento Krusty y pronto el verano se vuelve una pesadilla.',24,59),
    (2,'Un tranvía llamado Marge',4,'Marge gana el rol protagónico en un musical, Maggie pierde el chupete en la guardería.',24,60),
    (3,'Homero hereje',4,'Homero incendia la casa y lo terminan salvando los bomberos voluntarios.',24,61),
    (4,'La reina de la belleza',4,'Lisa entra a un concurso de belleza para recuperar la autoestima luego de un retrato espantoso.',24,62),
    (5,'Las casitas del terror III',4,'El muñeco de Krusty enloquese, y Lisa llena la ciudad de zombis tratando de revivir a su gato.',24,63),
    (6,'Tomy y Daly, la película',4,'Bart se porta muy mal, por lo que Homero le prohíbe ver la nueva película de Tomy y Daly.',24,64),
    (7,'Marge consigue empleo',4,'El señor Burns se enamora de Marge. Mientras tanto, Bart grita que vio un lobo… literalmente.',24,65),
    (8,'La chica nueva',4,'Bart se enamora de su nueva vecina adolescente, Mientras, Homero demanda a un restaurante de mariscos',23,66),
    (9,'Don Barredora',4,'Homero y Barney compiten por la nieve: me llama usted, entonces voy, Don Barredora es quien yo soy.',24,67),
    (10,'La primera palabra de Maggie',4,'En una retrospectiva, el pequeño Bart se muere de celos cuando Lisa llega a la familia.',24,68),
    (11,'El gran corazón de Homero',4,'Homero necesita una operación de bypass… y un medico que le haga un descuento.',24,69),
    (12,'Marge contra el monorriel',4,'El monorriel promete llegar a Springfield con bombos y platillos, pero Marge huele algo raro.',24,70),
    (13,'La elección de Selma',4,'Los Simpson van a un funeral, y Selma empieza preguntarse sobre la vida y la maternidad.',24,71),
    (14,'Hermano mayor, hermano menor',4,'Bart consigue un hermano mayor que lo cuida, y Homero se busca un hermano menor solo por celos.',24,72),
    (15,'Yo amo a Lisa',4,'Lisa le da una tarjeta de San Valentín a Rafa, que se enamora de ella.',24,73),
    (16,'La promesa',4,'Arrestan a Homero por conducir alcoholizado, y él aprovecha para ver cómo es la vida sin cerveza.',24,74),
    (17,'La última salida a Springfield',4,'Burns quiere sacarles los beneficios a los empleados. ¡Plan dental! Lisa necesita frenos…',24,75),
    (18,'A esto hemos llegado',4,'Homero termina en el hospital por una broma de Bart, y la vida le pasa por delante de los ojos.',24,76),
    (19,'El intermedio',4,'Bart y Lisa escriben episodios de Tomy y Daly a través del abuelo, que se los envía al estudio.',24,77),
    (20,'El Día del Garrote',4,'Barry White y Lisa salvan a las víboras del Dia del Garrote. A Bart lo echan de la escuela.',24,78),
    (21,'Marge en cadenas',4,'Marge no paga algo en la tienda y termina en la cárcel. Ahora, la familia debe cuidarse sola…',24,79),
    (22,'El drama de Krusty',4,'Krusty pierde el programa y tiene que hacer un especial para salvar su carrera.',24,80),
    (1,'El cuarteto de Homero',5,'Los Simpson descubren un viejo álbum de Los Borbotones… y un coro de ángeles que incluyen a Homero.',24,81),
    (2,'Cabo de miedosos',5,'Bart recibe amenazas anónimas, y los Simpson sospechan de un viejo conocido.',24,82),
    (3,'Homero va a la universidad',5,'Homero vuelve a la universidad con un objetivo claro: ¡rebelarse y festejar!',24,83),
    (4,'El oso de Burns',5,'Bart le da a Maggie el oso de peluche de la infancia de Burns, y empieza la batalla por la tendencia.',24,84),
    (5,'Las casitas del terror IV',5,'Burns vampiro invita a los Simpson a cenar, y Bart ve un gremlin en el autobús escolar.',24,85),
    (6,'Marge, la rebelde',5,'El jefe Górgory detiene a la vecina de Marge. Oh, oh… ¡Acelerador a fondo!',24,86),
    (7,'Filosofía bartiana',5,'Homero consigue una cama elástica, y los niños del barrio primero la disfrutan y después la sufren.',24,87),
    (8,'Exploradores a fuerza',5,'Bart y  Milhouse se unen a los exploradores. Homero y Ned los acompañan en un viaje en balsa.',24,88),
    (9,'La última tentación de Homero',5,'Homero tiene una compañera de trabajo nueva y hermosa, y Marge teme por su matrimonio.',24,89),
    (10,'$pringfield próspero, o el problema del juego',5,'Burns abre un casino en Springfield tras legalizarse el juego, y Marge pierde el control.',24,90),
    (11,'Homero detective',5,'Homero trata de atrapar a un ladrón muy escurridizo, y el abuelo le da información clave.',24,91),
    (12,'Bart se hace famoso',5,'Bart trabaja de asistente de Krusty y hace un sketch que lo catapulta a la fama.',24,92),
    (13,'Homero y Apu',5,'Apu está en problemas, y Homero lo acompaña hasta la India en busca de respuestas.',24,93),
    (14,'Lisa contra la Baby Malibú',5,'Lisa, molesta por el sexismo de las fases que dice la muñeca Stacy Malibú, rastra a su cradora.',24,94),
    (15,'Homero en el espacio profundo',5,'En el intento de enviar a un hombre común al espacio, Homero y Barney se vuelvel astronautas.',24,95),
    (16,'Homero ama a Flanders',5,'Homero cambia su opinión sobre Flanders porque lo invita a un partido.',24,96),
    (17,'Bart gana un elefante',5,'Bart gana un elefante que se porta mal y es incontrolable. Las otras mascotas sientes el abandono.',24,97),
    (18,'El heredero de Burns',5,'Burns hace audiciones para encontrar heredero, y Bart le vandaliza la mansión: ¡tenemos un ganador!',24,98),
    (19,'La canción de Skinner',5,'Skinner pierde su cargo y vuelve al ejército. Mientras tanto, lo reemplaza Ned Flanders.',24,99),
    (20,'El niño que sabia demasiado ',5,'Bart es testigo accidental de una pelea que involucra al sobrino del alcalde y termina en juicio.',24,100),
    (21,'El amante de Lady Bouvier',5,'El padre y el jefe de Homero compiten por la madre de Marge',24,101),
    (22,'Secretos de un buen matrimonio',5,'Homero va a clase de educación para adultos, pero termina enseñando en otra.',24,102),
    (1,'El diabólico Bart',6,'Homero instala una piscina en el jardín de la casa, y Bart se rompe una pierna probando un clavado.',24,103),
    (2,'La rival de Lisa',6,'Lisa recluta a Bart para saborear el proyecto de la nueva niña de la clase, que rivaliza con ella.',24,104),
    (3,'Recuerdos de amor',6,'Una charla familiar sobre el amor desencadena historias que terminan con corazones rotos.',24,105),
    (4,'La tierra de Tomy y Daly',6,'Bart y Lisa piden a sus padres ir a La tierra de Tomy y Daly, donde son atacados por robots.',24,106),
    (5,'El regreso de Bob Patiño',6,'Bob Patiño se postula como candidato a alcalde por el Partido Republicano de Springfield, y gana.',24,107),
    (6,'Las casitas del terror V',6,'Los Simpson van a cuidar la posada de Burns, y Homero enloquece.',24,108),
    (7,'La novia de Bart',6,'Culpan a Bart de robar el dinero de las limosnas de la iglesia, y Lisa debe probar su inocencia.',24,109),
    (8,'Lisa y los deportes',6,'Lisa se convierte en portera de hockey. Bart juega para otro equipo, y nace una rivalidad.',24,110),
    (9,'Homero el Malo',6,'Por error, acusan de acoso sexual a Homero, que se convierte en un paria.',24,111),
    (10,'El abuelo y la ineficiencia romántica',6,'El abuelo sale a vender un elixir con Homero y le revela que no fue un hijo planificado.',24,112),
    (11,'Miedo a volar',6,'Homero recibe boletos de avión gratis y descubre que Marge teme volar, entonces ella va a terapia.',24,113),
    (12,'Homero el Grande',6,'Homero se convierte en líder de los Magios, un culto con un inmenso poder secreto.',24,114),
    (13,'Y von Maggie son tres',6,'Homero cuenta cómo fue el nacimiento de Maggie.',24,115),
    (14,'El cometa de Bart',6,'Bart descubre un cometa que resulta estar en trayectoria de colisión con la Tierra.',24,116),
    (15,'Homie, el payaso',6,'Homero se parece a Krusty, y eso le da beneficios hasta que llegan unos mafiosos y lo secuestran.',24,117),
    (16,'Bart contra Australia',6,'Bart va a Autralia para disculparse por una broma, pero le muestra el trasero al primer ministro.',24,118),
    (17,'Homero contra Patty y Selma',6,'Homero le pide un préstamo a las hermanas de Marge, que eligen la humillación como forma de pago.',24,119),
    (18,'Una estrella estrellada',6,'Un crítico de cine llega a Springfield para un festival con películas locales en competencia.',24,120),
    (19,'La boda de Lisa',6,'Una adivina predice el compromiso de Lisa con un compañero de estudio de la aristocracia británica.',24,121),
    (20,'Un galgo llamado Monty',6,'Los Simpson terminados con veinticinco cachorros, pero Burns los quiere para fines malvados.',24,122),
    (21,'Lucha educativa',6,'Los maestros de la escuela de Springfield hacen huelga, y los padres intervienen y dan las clases.',24,123),
    (22,'Por la ciudad de Springfield',6,'Lisa visita a Bart en el hospital y descubre que Encías Sangrantes también está ahí.',24,124),
    (23,'Contacto en Springfield',6,'Marge se hace policía y descubre que el trabajo no es tan divertido como ella esperaba.',24,125),
    (24,'El limón de Troya',6,'Unos niños de Shelbyville roban el famoso limonero de Springfield, y Bart promete recuperarlo.',24,126),
    (25,'¿Quién mató al Sr. Burns? 1Ra parte',6,'Burns misteriosamente recibe un disparo en el pecho, y no son pocos los sospechosos.',24,127),
    (1,'¿Quién mató al Sr. Burns? 2Da parte',7,'El jefe Górgory investiga quién le disparó al señor Burns en un episodio que parodia dramas de TV.',25,128),
    (2,'El Hombre Radioactivo',7,'Llega el rodaje de una película de superhéroes, y Milhouse consigue el rol de compinche.',24,129),
    (3,'Hogar, dulce hogarcirijillo',7,'Luego de varias desventajas, los niños Simpson quedan bajo la custodia de Ned y Maude Flanders.',24,130),
    (4,'Bart vende su alma',7,'Bart le vende el alma a Milhouse por cinco dólares y luego se arrepiente.',24,131),
    (5,'Lisa, la vegetariana',7,'Lisa ya no puede comer cordero, entonces sus amigos y Homero se burlan de ella.',24,132),
    (6,'La casitas del terror VI',7,'Anuncios Atacan Springfield, Willie aterroriza a los niños y Homero entra al mundo tridimensional.',24,133),
    (7,'Homero tamaño familiar',7,'Homero engorda para tener beneficios de incapacidad y trabajar desde casa, pero todos se derrumba.',24,134),
    (8,'Mamá Simpson',7,'Reaparece la madre de Homero, y la familia descubre que era una radical en los sesenta.',24,135),
    (9,'La última carcajada de Bob Patiño',7,'Bov Patiño regresa y trata de destruir a a Krusty con el avión de los hermanos Wright.',24,136),
    (10,'El episodio espectacular 138',7,'Un episodio con videos nunca antes vistos y finales alternativos de “¿Quién mato al señor Burns?”.',24,137),
    (11,'El bebé de mamá',7,'Bart cae preso por robar y decepciona a Marge, entonces se desespera por recuperar su respeto.',24,138),
    (12,'El equipo de Homero',7,'Homero se ve obligado a incluir al señor Burns en el equipo de bolos por el dinero de la adminsíon.',24,139),
    (13,'El mal vecino',7,'El expresidente George H. W. Bush compra la casa de enfrente de los Simpson.',24,140),
    (14,'Lucha de clases en Springfield',7,'Homero descubre que el señor Burns hace trampa en el golf, y Marge no encaja en la clase alta.',24,141),
    (15,'Bart, el soplón',7,'Krusty el Payaso finge su muerte, y Bart intenta convencerlo de volver a la sociedad.',24,142),
    (16,'Lisa, la iconoclasta ',7,'Lisa descubre que Jeremías Springfield, el fundador de la ciudad, fue un hombre terrible.',24,143),
    (17,'Homero Smithers',7,'Tras despedir a Smithers, el señor Burns se accidenta y depende, otra vez, de su antiguo asistente.',24,144),
    (18,'El día que murió la violencia',7,'Bart conoce el creador de Tomy y Daly y lo ayuda a demandar al estudio que tiene los derechos.',24,145),
    (19,'El sueño de amor de Selma',7,'Troy McClure se casa con la hermana de Marge para ocultarse al mundo su peculiar fetiche sexual.',24,146),
    (20,'Bart recorre el mundo',7,'Bart falsifica una licencia de conducir y conduce hasta Knoxville, Tennessee.',24,147),
    (21,'Veintidós películas cortas sobre Springfield',7,'Skinner cena con su jefe, Maggie queda atrapada, y Nelson recibe su merecido.',24,148),
    (22,'Mi héroe, el abuelo',7,'El abuelo heredará una fortuna de su antigua unidad del ejército. Si el señor Burns muere antes.',24,149),
    (23,'¿Y dónde está el inmigrante?',7,'Spingfield le pone fin a la inmigración ilegal, y Apu estudia para la prueba de ciudadanía.',24,150),
    (24,'Reventón',7,'Homero hace una gira con bandas de rock y atrapa balas de cañón para entretener al público.',24,151),
    (25,'Yo amo a Lisa',7,'Lisa se vuelve popular por su nuevo grupo, y Bart se convierte en mala onda.',24,152)
;

SELECT * FROM capitulo;